version: "3.9"
services:
 db_take_me:
  image: mariadb:10.9.4
  restart: unless-stopped
  container_name: userDB
  ports:
   - 3306:3306
  volumes:
   - ./docker_file_take_me/init_db/:/docker-entrypoint-initdb.d/
  environment:
   - MARIADB_DATABASE=swtp
   - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
 